steps:
- name: gcr.io/cloud-builders/docker
  id: Build Image
  args: [
    'build',
    '-t','us-docker.pkg.dev/$PROJECT_ID/cicd-basic/cicd-basic:latest',
    '.'
  ]

- name: 'us-docker.pkg.dev/$PROJECT_ID/cicd-basic/cicd-basic:latest'
  id: Validation Test
  entrypoint: python
  args: ['-m','unittest','tests/test_calculate.py']

- name: gcr.io/cloud-builders/docker
  id: Push Image to AR
  args: ['push','us-docker.pkg.dev/$PROJECT_ID/cicd-basic/cicd-basic:latest']

options:
  logging: CLOUD_LOGGING_ONLY
